### ISSUE TITLE
file missing in repository

### ISSUE THREAD

**Issue by rocketbob** [InquisitorJax/Microsoft-Cognitive-Services-Face-Recognition#1]
APIKeyProvider.cs

**Comment by InquisitorJax** [comment]
Hey @rocketbob - that is by design, although perhaps I should be clearer about why.

Here's a sample of the file needed:
`public class ApiKeyProvider : IApiKeyProvider
    {
        public string GetApiKey(ApiKeyType keyType)
        {
            string key = null;

            switch (keyType)
            {
                case ApiKeyType.FaceApi:
                    key = <STRING_CODE_HERE>;
                    break;

                default:
                    throw new NotSupportedException("Cognitive service not supported!");
            }

            return key;
        }
    }`

**Comment by rocketbob** [comment]
Makes sense. Thank you!
